// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _127: x0 => x0.stopPropagation(),
      _128: x0 => x0.preventDefault(),
      _130: x0 => x0.remove(),
      _131: (x0,x1) => x0.append(x1),
      _132: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _177: x0 => x0.unlock(),
      _178: x0 => x0.getReader(),
      _179: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _180: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _181: (x0,x1) => x0.item(x1),
      _182: x0 => x0.next(),
      _183: x0 => x0.now(),
      _184: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._184(f,arguments.length,x0) }),
      _185: (x0,x1) => x0.addListener(x1),
      _186: (x0,x1) => x0.removeListener(x1),
      _187: (x0,x1) => x0.matchMedia(x1),
      _194: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._194(f,arguments.length,x0) }),
      _195: (x0,x1) => x0.getModifierState(x1),
      _196: (x0,x1) => x0.removeProperty(x1),
      _197: (x0,x1) => x0.prepend(x1),
      _198: x0 => new Intl.Locale(x0),
      _199: x0 => x0.disconnect(),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _209: (x0,x1) => x0.hasAttribute(x1),
      _210: (x0,x1) => x0.getModifierState(x1),
      _211: (x0,x1) => x0.createTextNode(x1),
      _212: (x0,x1) => x0.appendChild(x1),
      _213: (x0,x1) => x0.removeAttribute(x1),
      _214: x0 => x0.getBoundingClientRect(),
      _215: (x0,x1) => x0.closest(x1),
      _644: x0 => new Uint8Array(x0),
      _648: () => globalThis.window.flutterConfiguration,
      _650: x0 => x0.assetBase,
      _655: x0 => x0.canvasKitMaximumSurfaces,
      _656: x0 => x0.debugShowSemanticsNodes,
      _657: x0 => x0.hostElement,
      _658: x0 => x0.multiViewEnabled,
      _659: x0 => x0.nonce,
      _661: x0 => x0.fontFallbackBaseUrl,
      _671: x0 => x0.console,
      _672: x0 => x0.devicePixelRatio,
      _673: x0 => x0.document,
      _674: x0 => x0.history,
      _675: x0 => x0.innerHeight,
      _676: x0 => x0.innerWidth,
      _677: x0 => x0.location,
      _678: x0 => x0.navigator,
      _679: x0 => x0.visualViewport,
      _680: x0 => x0.performance,
      _684: (x0,x1) => x0.getComputedStyle(x1),
      _685: x0 => x0.screen,
      _686: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._686(f,arguments.length,x0) }),
      _687: (x0,x1) => x0.requestAnimationFrame(x1),
      _692: (x0,x1) => x0.warn(x1),
      _694: (x0,x1) => x0.debug(x1),
      _695: x0 => globalThis.parseFloat(x0),
      _696: () => globalThis.window,
      _697: () => globalThis.Intl,
      _698: () => globalThis.Symbol,
      _701: x0 => x0.clipboard,
      _702: x0 => x0.maxTouchPoints,
      _703: x0 => x0.vendor,
      _704: x0 => x0.language,
      _705: x0 => x0.platform,
      _706: x0 => x0.userAgent,
      _707: (x0,x1) => x0.vibrate(x1),
      _708: x0 => x0.languages,
      _709: x0 => x0.documentElement,
      _710: (x0,x1) => x0.querySelector(x1),
      _713: (x0,x1) => x0.createElement(x1),
      _716: (x0,x1) => x0.createEvent(x1),
      _717: x0 => x0.activeElement,
      _720: x0 => x0.head,
      _721: x0 => x0.body,
      _723: (x0,x1) => { x0.title = x1 },
      _726: x0 => x0.visibilityState,
      _727: () => globalThis.document,
      _728: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._728(f,arguments.length,x0) }),
      _729: (x0,x1) => x0.dispatchEvent(x1),
      _737: x0 => x0.target,
      _739: x0 => x0.timeStamp,
      _740: x0 => x0.type,
      _742: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _749: x0 => x0.firstChild,
      _753: x0 => x0.parentElement,
      _755: (x0,x1) => { x0.textContent = x1 },
      _756: x0 => x0.parentNode,
      _757: x0 => x0.nextSibling,
      _758: (x0,x1) => x0.removeChild(x1),
      _759: x0 => x0.isConnected,
      _767: x0 => x0.clientHeight,
      _768: x0 => x0.clientWidth,
      _769: x0 => x0.offsetHeight,
      _770: x0 => x0.offsetWidth,
      _771: x0 => x0.id,
      _772: (x0,x1) => { x0.id = x1 },
      _775: (x0,x1) => { x0.spellcheck = x1 },
      _776: x0 => x0.tagName,
      _777: x0 => x0.style,
      _779: (x0,x1) => x0.querySelectorAll(x1),
      _780: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _781: x0 => x0.tabIndex,
      _782: (x0,x1) => { x0.tabIndex = x1 },
      _783: (x0,x1) => x0.focus(x1),
      _784: x0 => x0.scrollTop,
      _785: (x0,x1) => { x0.scrollTop = x1 },
      _786: x0 => x0.scrollLeft,
      _787: (x0,x1) => { x0.scrollLeft = x1 },
      _788: x0 => x0.classList,
      _790: (x0,x1) => { x0.className = x1 },
      _792: (x0,x1) => x0.getElementsByClassName(x1),
      _793: x0 => x0.click(),
      _794: (x0,x1) => x0.attachShadow(x1),
      _797: x0 => x0.computedStyleMap(),
      _798: (x0,x1) => x0.get(x1),
      _804: (x0,x1) => x0.getPropertyValue(x1),
      _805: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _806: x0 => x0.offsetLeft,
      _807: x0 => x0.offsetTop,
      _808: x0 => x0.offsetParent,
      _810: (x0,x1) => { x0.name = x1 },
      _811: x0 => x0.content,
      _812: (x0,x1) => { x0.content = x1 },
      _830: (x0,x1) => { x0.nonce = x1 },
      _834: (x0,x1) => { x0.width = x1 },
      _837: (x0,x1) => { x0.height = x1 },
      _840: (x0,x1) => x0.getContext(x1),
      _908: x0 => x0.width,
      _909: x0 => x0.height,
      _911: (x0,x1) => x0.fetch(x1),
      _912: x0 => x0.status,
      _914: x0 => x0.body,
      _915: x0 => x0.arrayBuffer(),
      _918: x0 => x0.read(),
      _919: x0 => x0.value,
      _920: x0 => x0.done,
      _928: x0 => x0.x,
      _929: x0 => x0.y,
      _932: x0 => x0.top,
      _933: x0 => x0.right,
      _934: x0 => x0.bottom,
      _935: x0 => x0.left,
      _945: x0 => x0.height,
      _946: x0 => x0.width,
      _947: x0 => x0.scale,
      _948: (x0,x1) => { x0.value = x1 },
      _951: (x0,x1) => { x0.placeholder = x1 },
      _952: (x0,x1) => { x0.name = x1 },
      _954: x0 => x0.selectionDirection,
      _955: x0 => x0.selectionStart,
      _956: x0 => x0.selectionEnd,
      _959: x0 => x0.value,
      _961: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _962: x0 => x0.readText(),
      _963: (x0,x1) => x0.writeText(x1),
      _965: x0 => x0.altKey,
      _966: x0 => x0.code,
      _967: x0 => x0.ctrlKey,
      _968: x0 => x0.key,
      _969: x0 => x0.keyCode,
      _970: x0 => x0.location,
      _971: x0 => x0.metaKey,
      _972: x0 => x0.repeat,
      _973: x0 => x0.shiftKey,
      _974: x0 => x0.isComposing,
      _976: x0 => x0.state,
      _977: (x0,x1) => x0.go(x1),
      _979: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _980: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _981: x0 => x0.pathname,
      _982: x0 => x0.search,
      _983: x0 => x0.hash,
      _987: x0 => x0.state,
      _994: x0 => new MutationObserver(x0),
      _995: (x0,x1,x2) => x0.observe(x1,x2),
      _996: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._996(f,arguments.length,x0,x1) }),
      _999: x0 => x0.attributeName,
      _1000: x0 => x0.type,
      _1001: x0 => x0.matches,
      _1002: x0 => x0.matches,
      _1006: x0 => x0.relatedTarget,
      _1008: x0 => x0.clientX,
      _1009: x0 => x0.clientY,
      _1010: x0 => x0.offsetX,
      _1011: x0 => x0.offsetY,
      _1014: x0 => x0.button,
      _1015: x0 => x0.buttons,
      _1016: x0 => x0.ctrlKey,
      _1020: x0 => x0.pointerId,
      _1021: x0 => x0.pointerType,
      _1022: x0 => x0.pressure,
      _1023: x0 => x0.tiltX,
      _1024: x0 => x0.tiltY,
      _1025: x0 => x0.getCoalescedEvents(),
      _1028: x0 => x0.deltaX,
      _1029: x0 => x0.deltaY,
      _1030: x0 => x0.wheelDeltaX,
      _1031: x0 => x0.wheelDeltaY,
      _1032: x0 => x0.deltaMode,
      _1039: x0 => x0.changedTouches,
      _1042: x0 => x0.clientX,
      _1043: x0 => x0.clientY,
      _1046: x0 => x0.data,
      _1049: (x0,x1) => { x0.disabled = x1 },
      _1051: (x0,x1) => { x0.type = x1 },
      _1052: (x0,x1) => { x0.max = x1 },
      _1053: (x0,x1) => { x0.min = x1 },
      _1054: x0 => x0.value,
      _1055: (x0,x1) => { x0.value = x1 },
      _1056: x0 => x0.disabled,
      _1057: (x0,x1) => { x0.disabled = x1 },
      _1059: (x0,x1) => { x0.placeholder = x1 },
      _1061: (x0,x1) => { x0.name = x1 },
      _1063: (x0,x1) => { x0.autocomplete = x1 },
      _1064: x0 => x0.selectionDirection,
      _1065: x0 => x0.selectionStart,
      _1067: x0 => x0.selectionEnd,
      _1070: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1071: (x0,x1) => x0.add(x1),
      _1074: (x0,x1) => { x0.noValidate = x1 },
      _1075: (x0,x1) => { x0.method = x1 },
      _1076: (x0,x1) => { x0.action = x1 },
      _1102: x0 => x0.orientation,
      _1103: x0 => x0.width,
      _1104: x0 => x0.height,
      _1105: (x0,x1) => x0.lock(x1),
      _1124: x0 => new ResizeObserver(x0),
      _1127: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1127(f,arguments.length,x0,x1) }),
      _1135: x0 => x0.length,
      _1136: x0 => x0.iterator,
      _1137: x0 => x0.Segmenter,
      _1138: x0 => x0.v8BreakIterator,
      _1139: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1142: x0 => x0.language,
      _1143: x0 => x0.script,
      _1144: x0 => x0.region,
      _1162: x0 => x0.done,
      _1163: x0 => x0.value,
      _1164: x0 => x0.index,
      _1168: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1169: (x0,x1) => x0.adoptText(x1),
      _1170: x0 => x0.first(),
      _1171: x0 => x0.next(),
      _1172: x0 => x0.current(),
      _1186: x0 => x0.hostElement,
      _1187: x0 => x0.viewConstraints,
      _1190: x0 => x0.maxHeight,
      _1191: x0 => x0.maxWidth,
      _1192: x0 => x0.minHeight,
      _1193: x0 => x0.minWidth,
      _1194: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1194(f,arguments.length,x0) }),
      _1195: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1195(f,arguments.length,x0) }),
      _1196: (x0,x1) => ({addView: x0,removeView: x1}),
      _1199: x0 => x0.loader,
      _1200: () => globalThis._flutter,
      _1201: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1202: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1202(f,arguments.length,x0) }),
      _1203: f => finalizeWrapper(f, function() { return dartInstance.exports._1203(f,arguments.length) }),
      _1204: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1207: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1207(f,arguments.length,x0) }),
      _1208: x0 => ({runApp: x0}),
      _1210: (x0,x1,x2) => x0.call(x1,x2),
      _1211: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1211(f,arguments.length,x0,x1) }),
      _1212: x0 => new Promise(x0),
      _1213: x0 => x0.length,
      _1276: x0 => x0.createRange(),
      _1277: (x0,x1) => x0.selectNode(x1),
      _1278: x0 => x0.getSelection(),
      _1279: x0 => x0.removeAllRanges(),
      _1280: (x0,x1) => x0.addRange(x1),
      _1281: (x0,x1) => x0.createElement(x1),
      _1282: (x0,x1) => x0.append(x1),
      _1283: (x0,x1,x2) => x0.insertRule(x1,x2),
      _1284: (x0,x1) => x0.add(x1),
      _1285: x0 => x0.preventDefault(),
      _1286: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1286(f,arguments.length,x0) }),
      _1287: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1295: Date.now,
      _1297: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1298: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1299: () => {
        let stackString = new Error().stack.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1300: () => typeof dartUseDateNowForTicks !== "undefined",
      _1301: () => 1000 * performance.now(),
      _1302: () => Date.now(),
      _1305: () => new WeakMap(),
      _1306: (map, o) => map.get(o),
      _1307: (map, o, v) => map.set(o, v),
      _1308: x0 => new WeakRef(x0),
      _1309: x0 => x0.deref(),
      _1316: () => globalThis.WeakRef,
      _1320: s => JSON.stringify(s),
      _1321: s => printToConsole(s),
      _1322: (o, p, r) => o.replaceAll(p, () => r),
      _1324: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1325: s => s.toUpperCase(),
      _1326: s => s.trim(),
      _1327: s => s.trimLeft(),
      _1328: s => s.trimRight(),
      _1329: (string, times) => string.repeat(times),
      _1330: Function.prototype.call.bind(String.prototype.indexOf),
      _1331: (s, p, i) => s.lastIndexOf(p, i),
      _1332: (string, token) => string.split(token),
      _1333: Object.is,
      _1337: (o, c) => o instanceof c,
      _1338: o => Object.keys(o),
      _1368: x0 => new Array(x0),
      _1370: x0 => x0.length,
      _1372: (x0,x1) => x0[x1],
      _1373: (x0,x1,x2) => { x0[x1] = x2 },
      _1376: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1378: x0 => new Int8Array(x0),
      _1379: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1381: x0 => new Uint8ClampedArray(x0),
      _1383: x0 => new Int16Array(x0),
      _1385: x0 => new Uint16Array(x0),
      _1387: x0 => new Int32Array(x0),
      _1389: x0 => new Uint32Array(x0),
      _1391: x0 => new Float32Array(x0),
      _1393: x0 => new Float64Array(x0),
      _1399: x0 => x0.random(),
      _1402: () => globalThis.Math,
      _1415: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1416: (handle) => clearTimeout(handle),
      _1419: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1421: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1422: (x0,x1) => x0.exec(x1),
      _1423: (x0,x1) => x0.test(x1),
      _1424: x0 => x0.pop(),
      _1426: o => o === undefined,
      _1428: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1430: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1431: o => o instanceof RegExp,
      _1432: (l, r) => l === r,
      _1433: o => o,
      _1434: o => o,
      _1435: o => o,
      _1436: b => !!b,
      _1437: o => o.length,
      _1439: (o, i) => o[i],
      _1440: f => f.dartFunction,
      _1441: () => ({}),
      _1442: () => [],
      _1444: () => globalThis,
      _1445: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1447: (o, p) => o[p],
      _1448: (o, p, v) => o[p] = v,
      _1449: (o, m, a) => o[m].apply(o, a),
      _1451: o => String(o),
      _1452: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1453: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1453(f,arguments.length,x0) }),
      _1454: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1454(f,arguments.length,x0,x1) }),
      _1455: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1456: o => [o],
      _1457: (o0, o1) => [o0, o1],
      _1458: (o0, o1, o2) => [o0, o1, o2],
      _1459: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1460: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1461: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1464: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1465: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1466: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1467: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1468: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1469: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1470: x0 => new ArrayBuffer(x0),
      _1471: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1473: x0 => x0.index,
      _1475: x0 => x0.flags,
      _1476: x0 => x0.multiline,
      _1477: x0 => x0.ignoreCase,
      _1478: x0 => x0.unicode,
      _1479: x0 => x0.dotAll,
      _1480: (x0,x1) => { x0.lastIndex = x1 },
      _1481: (o, p) => p in o,
      _1482: (o, p) => o[p],
      _1485: o => o instanceof Array,
      _1490: a => a.pop(),
      _1491: (a, i) => a.splice(i, 1),
      _1492: (a, s) => a.join(s),
      _1493: (a, s, e) => a.slice(s, e),
      _1496: a => a.length,
      _1498: (a, i) => a[i],
      _1499: (a, i, v) => a[i] = v,
      _1501: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1502: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1504: o => o instanceof Uint8Array,
      _1505: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1506: o => o instanceof Int8Array,
      _1507: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1508: o => o instanceof Uint8ClampedArray,
      _1509: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1510: o => o instanceof Uint16Array,
      _1511: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1512: o => o instanceof Int16Array,
      _1513: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1514: o => o instanceof Uint32Array,
      _1515: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1516: o => o instanceof Int32Array,
      _1517: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1519: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1520: o => o instanceof Float32Array,
      _1521: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1522: o => o instanceof Float64Array,
      _1523: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1524: (t, s) => t.set(s),
      _1526: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1528: o => o.buffer,
      _1529: o => o.byteOffset,
      _1530: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1531: (b, o) => new DataView(b, o),
      _1532: (b, o, l) => new DataView(b, o, l),
      _1533: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1534: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1535: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1536: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1537: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1538: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1539: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1540: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1541: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1542: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1543: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1544: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1547: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1548: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1549: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1550: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1551: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1552: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1553: Function.prototype.call.bind(Number.prototype.toString),
      _1554: Function.prototype.call.bind(BigInt.prototype.toString),
      _1555: Function.prototype.call.bind(Number.prototype.toString),
      _1556: (d, digits) => d.toFixed(digits),
      _1560: () => globalThis.document,
      _1561: () => globalThis.window,
      _1566: (x0,x1) => { x0.height = x1 },
      _1568: (x0,x1) => { x0.width = x1 },
      _1571: x0 => x0.head,
      _1572: x0 => x0.classList,
      _1576: (x0,x1) => { x0.innerText = x1 },
      _1577: x0 => x0.style,
      _1579: x0 => x0.sheet,
      _1590: x0 => x0.offsetX,
      _1591: x0 => x0.offsetY,
      _1592: x0 => x0.button,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      S: new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
